version: '2.2'

services:
  generate-ssl-stores:
    build: ./docker/generate-ssl-stores
    volumes:
      - ./resource/generic_ca_cert.conf:/usr/src/app/generic_ca_cert.conf
      - ./ssl-stores:/usr/src/app/ssl-stores

  cassandra:
    image: cassandra:3.11
    env_file:
      - docker/cassandra/cassandra.env
    mem_limit: 4g
    memswap_limit: 4g
    mem_swappiness: 0
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
    volumes:
      - ./data/cassandra:/var/lib/cassandra
      - ./docker/cassandra/jmxremote.access:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/management/jmxremote.access
      - ./docker/cassandra/jmxremote.password:/etc/cassandra/jmxremote.password

  cassandra-ssl:
    image: cassandra-ssl
    build:
      context: ./docker/cassandra-ssl
      args:
        KEY_STORE_PWD: "keypassword"
        TRUST_STORE_PWD: "trustpassword"
    env_file:
          - docker/cassandra-ssl/cassandra.env
    mem_limit: 4g
    memswap_limit: 4g
    mem_swappiness: 0
    ports:
      - "222:22"
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
    volumes:
      - ./data/cassandra-ssl:/var/lib/cassandra
      - ./docker/cassandra-ssl/jmxremote.access:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/management/jmxremote.access
      - ./docker/cassandra-ssl/jmxremote.password:/etc/cassandra/jmxremote.password
      - ./ssl-stores/node-server-keystore.jks:/etc/ssl/node-server-keystore.jks
      - ./ssl-stores/generic-server-truststore.jks:/etc/ssl/generic-server-truststore.jks

  cqlsh:
    image: cassandra:3.11
    command: cqlsh cassandra
    links:
      - cassandra

  nodetool:
    image: cassandra:3.11
    entrypoint: nodetool --host cassandra --username reaperUser --password reaperPass
    links:
      - cassandra

  nodetool-ssl:
      image: cassandra-ssl
      entrypoint: nodetool --host cassandra-ssl --username cassandraUser --password cassandraPass --ssl
      links:
        - cassandra-ssl
      volumes:
        - ./ssl-stores/node-server-keystore.jks:/etc/ssl/node-server-keystore.jks
        - ./ssl-stores/generic-server-truststore.jks:/etc/ssl/generic-server-truststore.jks

  initialize-reaper_db:
    build: ./docker/initialize-reaper_db
    links:
      - cassandra

  initialize-reaper_db-ssl:
    build: ./docker/initialize-reaper_db-ssl
    links:
      - cassandra-ssl

  reaper:
    image: cassandra-reaper:latest
    env_file:
      - docker/reaper/reaper.env
    links:
      - cassandra
    ports:
      - "8080:8080"
      - "8081:8081"

  reaper-ssl:
    image: cassandra-reaper:latest
    env_file:
      - docker/reaper-ssl/reaper-ssl.env
    links:
      - cassandra-ssl
    volumes:
      - ./ssl-stores/node-server-keystore.jks:/etc/ssl/node-server-keystore.jks
      - ./ssl-stores/generic-server-truststore.jks:/etc/ssl/generic-server-truststore.jks
    ports:
      - "8080:8080"
      - "8081:8081"